# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Update Psalm baseline

on:
  workflow_dispatch:
  schedule:
    - cron: "5 2 * * *"

jobs:
  update-psalm-baseline:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    strategy:
      fail-fast: false
      matrix:
        branches: ['master', 'stable29', 'stable28', 'stable27']

    name: update-psalm-baseline-${{ matrix.branches }}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ matrix.branches }}
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 #v2.31.1
        with:
          php-version: '8.1'
          extensions: apcu,ctype,curl,dom,fileinfo,ftp,gd,intl,json,ldap,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer install

      - name: Psalm
        run: composer run psalm:ci -- --monochrome --no-progress --output-format=text --update-baseline
        continue-on-error: true

      - name: Psalm OCP
        run: composer run psalm:ci -- -c psalm-ocp.xml --monochrome --no-progress --output-format=github --update-baseline
        continue-on-error: true

      - name: Reset composer
        run: |
          git clean -f lib/composer
          git checkout composer.json composer.lock lib/composer

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          token: ${{ secrets.COMMAND_BOT_PAT }}
          commit-message: 'chore(tests): Update psalm baseline'
          committer: GitHub <noreply@github.com>
          author: nextcloud-command <nextcloud-command@users.noreply.github.com>
          signoff: true
          branch: 'automated/noid/${{ matrix.branches }}-update-psalm-baseline'
          title: '[${{ matrix.branches }}] Update psalm-baseline.xml'
          body: |
            Auto-generated update psalm-baseline.xml with fixed psalm warnings
          labels: |
            automated pr
            3. to review
          team-reviewers: server-backend
